spring.subscriptionApp.name=subscription-app

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway (reativado)
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
spring.flyway.url=${SPRING_DATASOURCE_URL}
spring.flyway.user=${SPRING_DATASOURCE_USERNAME}
spring.flyway.password=${SPRING_DATASOURCE_PASSWORD}

# Debug Flyway
logging.level.org.flywaydb=DEBUG

spring.docker.compose.file=../compose.yaml
